### ISSUE TITLE
Import media-files from other sources

### ISSUE THREAD

**Issue by Joey-2001** [xantari/PinCabScreenConfigurator#19]
At the moment only mediafiles from vpforums are insert in the database.
It would be nice, if other ressources would be added like Popper-mediadatabase or MEGA-accounts from different users.
I upload my mediafiles (at the moment nearly 9.000 files) to MEGA and Popper.
So if it is possible, ask David Paiva (nailbuster) to import links from Popper. And I can give you the links to my MEGA-account.

Filemanager in Popper
[REDACTED, screenshot is from a private server]

**Comment by xantari** [comment]
Thanks!

I'll check where this popper data is located and try get it added as a separate database. I do know there is a pupmedia.php endpoint hosted on vpinball.com that I planned on hooking into for media, so i'm wondering if this screenshot is pulling from the same location (I haven't had time to look at it yet).

As for mega links, I was hoping that those would remain in the VPS Spreadsheet. For instance a lot of the wheel art files in VPS spreadsheet points to mega links. 

If your links are not in the VPS (Dux Retro) spreadsheet I could consider adding a "custom" database option and additions/subtractions to the list could be requested from users by doing Github pull requests into the .json file.

**Comment by Joey-2001** [comment]
The screenshot is from the popper mediabase. You need an account to see it. To get an account, you can ask David Paiva. But maybe there is another solution, to load the data.

**Comment by xantari** [comment]
Sorry for my naïveté on pinup popper as I haven't got it setup yet. I browsed the various menus in pinup popper and don't see how to access the mediabase program.

Do you have documentation on this functionality somewhere?

**Comment by xantari** [comment]
FYI, pinup popper hookins is a no-go. Looks like they want  this locked down to only pinup popper. I can see about adding a "custom" database so you can create your own database though with a simple UI to add/edit your own database entries.

**Comment by xantari** [comment]
@Joey-2001 I spent a considerable amount of time re-designing the database browser and database format to make it simpler and added all the functionality to the program to crowd source a database in a similar fashion to the VPS spreadsheet using Github as the delivery vehicle.

Full documentation is here: https://github.com/xantari/PinCab.Configurator/wiki/Database-Browser

I believe this will satisfy this request as it allows anyone to create databases now in a prescribed format that is fast and easy to consume. There are quite a few advantages of doing a database this way versus the spreadsheet way as we can ensure better data integrity and data standardization among other things listed in the documentation above.
